name: host-and-port
version: !include ./version.yaml
synopsis: Data type and utilities for handling host name and port number pairs
description: |
  This package provides:

  * Generic data type for storing host name and port number that uses phantom
    types to distinguish between server\/client, and various
    protocols\/services\/APIs.

  * Type classes for accessing host name and port number in a data type using
    lenses.

  * Generic parsing of host name and port number from e.g. command line
    arguments.

copyright: (c) 2017-2024 Peter Trško
maintainer: Peter Trško <peter.trsko@gmail.com>
license: BSD3
license-file: LICENSE
github: trskop/host-and-port
category: Data

tested-with: GHC == 9.4.1, GHC == 9.6.6

extra-source-files:
  - ChangeLog.md
  - README.md
  - dhall/**/*

ghc-options:
  - "-Wall"
  - "-Wcompat" # GHC ≥8.0
  - "-Wimplicit-prelude" # GHC ≥6.8
  - "-Wincomplete-record-updates" # GHC ≥6.4
  - "-Wmissing-deriving-strategies" # GHC ≥8.8
  - "-Wpartial-fields" # GHC ≥8.4
  - "-Wredundant-record-wildcards" # GHC ≥8.10
  - "-Wunused-packages" # GHC ≥8.10
  - "-Wunused-record-wildcards" # GHC ≥8.10

default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - ImportQualifiedPost # GHC >8.10
  - InstanceSigs
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators

flags:
  dhall:
    description: Provide support for Dhall.
    manual: false
    default: true

  pedantic:
    description: Turn on additional warning flags
    manual: true
    default: false

when:
  - condition: flag(pedantic)
    ghc-options:
      # Auto-generated files do not turn off this warning locally and it cannot
      # be fixed easily.
      - "-Wprepositive-qualified-module" # GHC ≥8.10

  - condition: flag(dhall)
    dependencies:
      - dhall >= 1.33.0
      # ^ Inject/Interpret were renamed to ToDhall/FromDhall in version 1.27.0
      # (standard 11.0.0), we can't go below that now as we use the new names.
      #
      # Bultins `Optional/{fold,build}` were removed in version 1.33.0
      # (standard 17.0.0), while this should not affect the code here, it does
      # make binary serialisation incompatible when it comes to more
      # complicated use cases. To prevent major issues we need to depend on at
      # least this version.
      #
      # Version 1.36.0 added `Text/replace` and made `with` a first class
      # citizen.  While we may want to depend on these features in the future,
      # if we limit our selves to standard 17.0.0 we should still be
      # compatible, unlike in the case of removed `Optional/{fold,build}`.
    cpp-options:
      -DDHALL

dependencies:
  - base >=4.17 && <5
  # ^ Why this version bounds:
  #
  # * Version 4.9.0.0 is the first one that introduced `Data.Functor.Classes`
  #   module, it's bundled with GHC >=8.
  # * Version 4.17.0.0 is the first one that supports GHC Proposal #371 and
  #   exports `~` via `Data.Type.Equality` module. This version is bundled with
  #   GHC 9.4.1.

# All the dependencies that we use with version bounds. This keeps them all
# consistent by the virtue of sharing.
_dependencies:
  - &generic-lens      "generic-lens >=1.0.0.2 && <3"
  # ^ Version 1.0.0.2 fixed compile-time performance issue.
  - &hostname-validate "hostname-validate >=1.0.0 && <2"
  # ^ At the time of writing 1.0.0 was the only available version.
  - &iproute           "iproute >=1.4.0 && <2"
  # ^ We depend on `IP` data type, which has been introduced in version 1.0.0
  # and hadn't changed since. Instance `Eq IP` is correctly defined starting
  # version 1.4.0.
  - &streaming-commons "streaming-commons >=0.1.0.0 && <1"
  # ^ We define `HasPort` instance. That type class was there unchanged since
  # version 0.1.0.0.
  #
  # We define code that uses `HostPreference` data type, which has been there
  # since version 0.1.0.0 and hasn't changed ever since.
  - &text              "text >=1.2.0.0 && <3"

library:
  source-dirs: src
  exposed-modules:
    - Data.HostAndPort
    - Data.HostAndPort.Class
    - Data.HostAndPort.Parse
    - Data.HostAndPort.Type

  dependencies:
    - *generic-lens
    - *hostname-validate
    - *iproute
    - *streaming-commons
    - *text

# tests:
  # spec:
    # cpp-options: -DTEST
    # main: Spec.hs
    # source-dirs:
      # - test
      # - src
    # dependencies:
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
