# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-13.27

packages:
  - '.'

#extra-deps: []

flags:
  host-and-port:
    dhall: true
    generic-lens: true
