# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# GHC 8.8.3
resolver: lts-16.3

packages:
  - '.'

extra-deps:
  - dhall-1.33.1
  - repline-0.4.0.0
  - haskeline-0.8.0.0

flags:
  host-and-port:
    dhall: true
    generic-lens: true
